version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: trelltech-postgres
    restart: always
    environment:
      POSTGRES_DB: trelltech
      POSTGRES_USER: trelltech_user
      POSTGRES_PASSWORD: trelltech_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
